eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
        instance:
            hostname: ${DOMAIN_NAME}