eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: https://imdb-discovery-server.herokuapp.com/eureka
        instance:
            hostname: imdb-discovery-server.herokuapp.com