eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            #defaultZone: http://localhost:8761/eureka/
            defaultZone: https://imdb-discovery-server.herokuapp.com/eureka
        instance:
            #hostname: localhost
            hostname: imdb-discovery-server.herokuapp.com